// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  active: string;
  selectOption: string;
}
export const cssExports: CssExports;
export default cssExports;
