// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bg-1': string;
  'bg-2': string;
  'bg-3': string;
  'bg-4': string;
  'bg-5': string;
  'bg-6': string;
  'bg-7': string;
  'bg-8': string;
  'bg-9': string;
  infoWrap: string;
  label: string;
  labelWrap: string;
  pictureWrap: string;
  root: string;
  statItem: string;
  statValue: string;
  statWrap: string;
  titleName: string;
}
export const cssExports: CssExports;
export default cssExports;
