// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  root: string;
  'sk-child': string;
  'sk-circle-10': string;
  'sk-circle-11': string;
  'sk-circle-12': string;
  'sk-circle-2': string;
  'sk-circle-3': string;
  'sk-circle-4': string;
  'sk-circle-5': string;
  'sk-circle-6': string;
  'sk-circle-7': string;
  'sk-circle-8': string;
  'sk-circle-9': string;
  'sk-circle-bounce': string;
  'sk-circle-bounce-delay': string;
}
export const cssExports: CssExports;
export default cssExports;
