// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  active: string;
  root: string;
  selectBody: string;
  selectPanel: string;
}
export const cssExports: CssExports;
export default cssExports;
