// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  activeLink: string;
  'hamburger-menu': string;
  menuLink: string;
  menuWrap: string;
  menu__box: string;
  menu__btn: string;
  menu__item: string;
  menu__toggle: string;
  open: string;
  pokemonLogo: string;
  root: string;
  wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
