// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  content: string;
  rocket__button: string;
  rocket__img: string;
  rocket__title: string;
  rocket__wrap: string;
  root: string;
  title: string;
  title__wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
