// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  light: string;
  pharagraph: string;
  root: string;
  wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
