// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  abilities: string;
  active: string;
  bottomBlock: string;
  cardWrap: string;
  descBlock: string;
  imageBlock: string;
  middleBlock: string;
  popUpClose: string;
  root: string;
  subtitle: string;
  title: string;
  topBlock: string;
  typeRow: string;
}
export const cssExports: CssExports;
export default cssExports;
