// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'pokedex-title': string;
  'pokemons-search': string;
  root: string;
  'search-bar': string;
}
export const cssExports: CssExports;
export default cssExports;
