// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  active: string;
  'active-slide': string;
  'active-slide__image': string;
  'active-slide__info': string;
  metric: string;
  'metric-line': string;
  'metric-line__all': string;
  'metric-line__item': string;
  name: string;
  next: string;
  'pokemon-desc': string;
  'pokemon-name': string;
  prev: string;
  root: string;
  slide: string;
  'slide-wrapper': string;
  slide__image: string;
  slide__name: string;
  'slider-arrow': string;
  'slider-title': string;
  'slides-block': string;
  stats: string;
  stats__item: string;
}
export const cssExports: CssExports;
export default cssExports;
